### ISSUE TITLE
Column "Feature"  empty

### ISSUE THREAD

**Issue by bertrandpons** [mmajcica/SpecFlowReportGeneratorTask#1]
Hi,

Thanks for this extension. 

I have an issue with the report. Please see below:

![image](https://user-images.githubusercontent.com/26971151/42946142-7c221c1a-8b6a-11e8-8005-39debcdb4546.png)

Do you have an idea about the column "Feature" being empty?

Thank you

Regards,

Bertrand

**Comment by mmajcica** [comment]
Hi,

this is usually happening once you generate your trx files for MS Test with VS Test. May that be your case?

**Comment by bertrandpons** [comment]
yes indeed.

Is there a way to fix that ?

**Comment by mmajcica** [comment]
There are multiple ways. Most common one is to use a different logger for vstest. I do mention this in my blog post here http://blog.majcica.com/2018/05/07/living-documentation-and-test-reports-in-vsts-tfs-pipelines/ and a logger that will generate the correct trx files can be found here (https://github.com/markvincze/MsTestTrxLogger) with some explanation in the following post https://blog.markvincze.com/how-to-fix-the-empty-specflow-html-report-problem-with-vstest-console-exe/

I hope this helps.

**Comment by bertrandpons** [comment]
Great! Many thanks for your help

**Comment by mmajcica** [comment]
You are welcome!
Don't forget to rate the extension on VSTS Marketplace! :)
